### ISSUE TITLE
&shy; gets removed when saving & reopening

### ISSUE THREAD

**Issue by franzrosenkohl** [sebkln/linebreak#2]
Your plugin works very well, however when I re-open a content element with a `&shy;` it gets stripped away, yielding only the empty containing `<div class="shy"></div>`.

I think the new editor is a huge step backward. YAML configuration is such a pain and basically none of the examples out there for ckeditor work at all.

**Comment by sebkln** [comment]
This should not be the case. Could you please check if the `&shy;` entity is still present in the frontend?

The switch to CKEditor has its pros and cons. Some people will have to work with YAML for the first time. Some features from the old EXT:rtehtmlarea are yet to be implemented. On the other side I like the way to add custom classes to elements, for example. And the configuration of the old RTE was quite a mess. I think EXT:rte_ckeditor will be further improved with TYPO3 v9.

**Comment by sebkln** [comment]
I'm closing this issue for now. You can re-open it if needed.
