### ISSUE TITLE
Not working inside UL and OL

### ISSUE THREAD

**Issue by Xippo** [sebkln/linebreak#4]
To fix this you have to add this to your typoscript:
lib.parseFunc_RTE {
           externalBlocks.ol{
		callRecursive = 1
		HTMLparser = 1
		HTMLparser.tags.span.fixAttrib.class.removeIfEquals = shy
		HTMLparser.rmTagIfNoAttrib = span
	}
	externalBlocks.li{
		callRecursive = 1
		HTMLparser = 1
		HTMLparser.tags.span.fixAttrib.class.removeIfEquals = shy
		HTMLparser.rmTagIfNoAttrib = span
	}
}

**Comment by sebkln** [comment]
Sorry for the late reply, and thank you for your feedback. I'll look into it and add it to the README.

**Comment by sebkln** [comment]
I can confirm this. It seems the addition for `<li>` elements are not needed, I added the `<ul>` instead.

> This issue didn't occur in my own website's content because there the `&shy;` entities were already inserted by the old RTE (without the wrapping `<span>`). Without the wrapper, the `&shy;` entities worked as expected in lists.
