### ISSUE TITLE
fix for issue #4 adds additional p tags around ul

### ISSUE THREAD

**Issue by mediaessenz** [sebkln/linebreak#5]
The fix for issue #4 adds additional p tags around ul and ol's.

With the fix, I get this output:
```
<ul>
  <p></p>
  <li>...</li>
  <li>...</li>
  <li>...</li>
  <p></p>
</ul>
```

Without the fix, I get this output:
```
<ul>
  <li>...</li>
  <li>...</li>
  <li>...</li>
</ul>
```
The source code of the ckeditor looks right (without p-tags)

**Comment by mediaessenz** [comment]
I think I found a solution.
Change the ul/ol part to
```
lib.parseFunc_RTE {
    externalBlocks {
        ul {        
           stdWrap.parseFunc {
               HTMLparser = 1
               HTMLparser.tags.span.fixAttrib.class.removeIfEquals = shy
               HTMLparser.rmTagIfNoAttrib = span
           }
        }
        ol < .ul
    }
}
```

**Comment by sebkln** [comment]
Thanks, I can confirm the issue. In my case the `<p>` tags were inside the `<ul>` element, though.

I tested your provided solution. While it removes the paragraphs, the wrapping span with `class="shy"` is no longer removed. Is it the same in your case?

**Comment by mediaessenz** [comment]
You are right, the p-tags are inside the ul and have no &nbsp; between.
I fixed this in the issue description.

And you are also right, that my solution is not working like expected.

**Comment by mediaessenz** [comment]
I think (again), that I found a solution.
Here my complete TS for this:
```
lib.parseFunc.allowTags := addToList(wbr)

lib.parseFunc_RTE {
	allowTags := addToList(wbr)
	nonTypoTagStdWrap {
		encapsLines.encapsTagList := addToList(li)
		HTMLparser {
			// Remove any 'shy' classes from <span> elements:
			tags.span.fixAttrib.class.removeIfEquals = shy
			// Remove all <span> elements which have no attribute:
			rmTagIfNoAttrib = span
		}
	}
	externalBlocks {
		ul {
			callRecursive = 1
			HTMLparser < lib.parseFunc_RTE.nonTypoTagStdWrap.HTMLparser
		}
		ol < .ul
	}
}
```
New is the line `encapsLines.encapsTagList := addToList(li)`

**Comment by sebkln** [comment]
Your TypoScript will work for lists with linebreaks on the first level. But on nested lists the empty paragraphs will return.

My attempts to find a fully working solution have not been successful (yet).

FYI: The final goal is to make this workaround obsolete. [The shy button did make its way into TYPO3 core again](https://review.typo3.org/#/c/57373/).

All this parseFunc magic is only needed to remove the `&shy;` wrapper. The goal is to remove the wrapper (it's polluting the database anyway) and just show the `&shy;` entity in the Source mode of the RTE, just like the non-breaking space `&nbsp;`. This must be done with JavaScript inside the plugin.

[TYPO3 Forge: Soft-hyphen (shy entity) should be visible in CKEditor](https://forge.typo3.org/issues/85391)

**Comment by sebkln** [comment]
I tested the new `parseFunc_RTE` TypoScript with several multiple nested lists (both `<ul>` and `<ol>`). These contained the `&shy;` entity and `wbr` tag, as well as some links to internal pages and mailto links.

With this example content I was no longer able to reproduce any issues in the frontend.

If the new TypoScript doesn't work for you, feel free to open a new issue with your setup and problem.
