### ISSUE TITLE
UL and OL parsefunc removes mailto: links in frontend

### ISSUE THREAD

**Issue by linawolf** [sebkln/linebreak#6]
since adding the following ts code:
```
// The same is needed for all occurrences inside lists:
lib.parseFunc_RTE.externalBlocks {
    ul {
        callRecursive = 1
        HTMLparser = 1
        HTMLparser.tags.span.fixAttrib.class.removeIfEquals = shy
        HTMLparser.rmTagIfNoAttrib = span
    }
    ol < .ul
}
```
a mailto: link inserted inside an ol or ul tag:
`<li>xyzabs <a href="mailto:info@example.de" title="xx">info@example.de</a> </li>`

Gets removed by the parseFunc in the frontend. However a link to a page like
`<li>xyzabc <a href="t3://page?uid=1" title="xx">yyy</a></li>`

does not get removed.

both links will be visible in the RTE and they do not disappear during saving but only when displaying the maillink in frontend.

When I remove the above typoscript the mail link will not be removed from the list, however the soft hyphens will not work in lists.

**Comment by sebkln** [comment]
Thanks for your report! I was able to reproduce the issue.

Can you check if the following changes fix your problem?

    lib.parseFunc_RTE.externalBlocks {
        ul.stdWrap {
            callRecursive = 1
            HTMLparser = 1
            HTMLparser {
                tags.span.fixAttrib.class.removeIfEquals = shy
                rmTagIfNoAttrib = span
                keepNonMatchedTags = 1
            }

        }
        ol < .ul
    }

Please mind the additional `stdWrap` after `ul` and the new `keepNonMatchedTags = 1`.

**Comment by sebkln** [comment]
I tested the new `parseFunc_RTE` TypoScript with several multiple nested lists (both `<ul>` and `<ol>`). These contained the `&shy;` entity and `wbr` tag, as well as some links to internal pages and mailto links.

With this example content I was no longer able to reproduce any issues in the frontend.

If the new TypoScript doesn't work for you, feel free to open a new issue with your setup and problem.

**Comment by linawolf** [comment]
Thanks a lot, works wonderfully with us.
