### ISSUE TITLE
Multiple inline styles dosen't work together

### ISSUE THREAD

**Issue by Xippo** [sebkln/linebreak#7]
Hi Sebastian thanks for your work on this Plugin.

I found an annoying bug when 2 different inline Styles are used. 

The DB entry shows
`<p><span class="big">Wir suchen Verstä<span class="shy">&shy;</span>rkung für unser Team und freuen uns darauf Sie kennen zu lernen !</span></p>`
and its rendered to
`<p><span class="big">Wir suchen Verstä­</span>rkung für unser Team und freuen uns darauf Sie kennen zu lernen !</p>`

probably this is some stuff inside the HTMLparser, i assume that the colsing tag is not removed correctly. 

You know some workaround or different setting?

The Projekt uses TYPO3 10.4.20 and the plugin setup is like the readme wants.

**Comment by sebkln** [comment]
Hi! I can reproduce the issue. For tests I deactivated the linebreak plugin – the plugin still exists.

It's either a matter of correct `parseFunc` configuration or an actual bug in the HTMLparser. I tried some settings, but to no effect: If two `<span>` elements are nested, always the outer/last closing tag is removed.

Do you want to file an issue on https://forge.typo3.org for that? I'll close this issue, as the plugin is not the problem source.
